apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teacher-service
  namespace: argocd
spec:
  project: education-platform
  source:
    repoURL: https://github.com/imenH-cloud/devops-education-platform
    targetRevision: main
    path: backend/teacher/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: education
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
